### ISSUE TITLE
Obviously bad channel not detected

### ISSUE THREAD

**Issue by wmvanvliet** [autoreject/autoreject#84]
I've been using autoreject to clean up a 24-subject Biosemi EEG dataset. So far, awesome results! However, I have a few subjects that have obviously bad channels, which are not detected properly in my current pipeline. Any idea's why?

Here is an example. I'm loading data like this:

```python
import mne
import autoreject
from functools import partial

raw = mne.io.read_raw_edf('my_subject.bdf, montage='biosemi32',
                          eog=['EXG1', 'EXG2', 'EXG3', 'EXG4'],
                          misc=['EXG5', 'EXG6', 'EXG7', 'EXG8'],
                          stim_channel='Status', preload=True)

# Apply the correct reference
raw = raw.set_eeg_reference(['EXG5', 'EXG6'])

# Bandpass filter
raw = raw.filter(0.5, 15, n_jobs=4)

# Extract epochs
events = mne.find_events(raw, mask=0xFF)
event_id = dict(related=6, unrelated=7)
epochs = mne.Epochs(raw, events, event_id, tmin=-0.2, tmax=1.0, baseline=(-0.2, 0), preload=True)
```

Plotting the evoked shows that channel AF3 (channel index 1) is bad:

![figure_1](https://user-images.githubusercontent.com/428273/32214994-4eaeef92-be29-11e7-80b2-6c8f181577ed.png)

Autoreject to the rescue! This is how I call it:

```python
picks = mne.pick_types(epochs.info, eeg=True)  # Find indices of all EEG channels
thresh_func = partial(autoreject.compute_thresholds, picks=picks, method='random_search')
ar = autoreject.LocalAutoRejectCV(n_interpolates=[1, 4, 8], picks=picks, thresh_func=thresh_func, cv=10)
ar.fit(epochs)
epochs = ar.transform(epochs)
```

This is the reject log:
![figure_2](https://user-images.githubusercontent.com/428273/32215072-92fda472-be29-11e7-9a98-ad8f128745c4.png)

And here is the "cleaned" data:
![figure_3](https://user-images.githubusercontent.com/428273/32215087-9c0fde36-be29-11e7-8509-8d8276826edc.png)

Are there any parameters I can tweak to make autoreject properly identify the broken channel? In the meanwhile, a good workaround is first doing RANSAC, which will detect the bad channel, before doing autoreject. But autoreject should be able to detect this channel, no? Contact me on w.m.vanvliet@gmail.com if you'd like the data.

**Comment by jasmainak** [comment]
Can you try `method='bayesian_optimization'` instead of `method='random_search'` to see if that works?

**Comment by wmvanvliet** [comment]
That did the trick!

![figure1](https://user-images.githubusercontent.com/428273/32217103-a513e7ec-be2f-11e7-86ba-c915cdc54837.png)
![figure2](https://user-images.githubusercontent.com/428273/32217110-aa9d21b0-be2f-11e7-9f03-67cca7b62bfb.png)

**Comment by jasmainak** [comment]
Nice!

**Comment by dengemann** [comment]
Hum ... this makes me wonder if it was right to change it to random search.
What was the reason again? Irreproducible findings and funky states ?
Hadn’t we fixed it then?

**Comment by wmvanvliet** [comment]
I still have a subject that has an obviously bad channel that is not properly detected. While changing to `method='bayesian_optimization'` improved matters, it did not fix the issue for all my subjects. Wouldn't it make sense to say that if a channel is bad for > 50% of the trials, it should just be interpolated for all of them? If I remember @dengemann 's talk at Aalto correctly, I thought that was the idea.

**Comment by dengemann** [comment]
That’s the intuition but it’s not as simple. It would be good to understand
what happens in your case.

**Comment by wmvanvliet** [comment]
I'll share the data with @jasmainak.

**Comment by wmvanvliet** [comment]
Here are the plots for the subject:

![figure_1](https://user-images.githubusercontent.com/428273/32266933-0f5856a2-bef2-11e7-9eff-c9edc4f5b77e.png)

The bad channel is C4, with index 22.

![figure_2](https://user-images.githubusercontent.com/428273/32266958-303d526e-bef2-11e7-972b-7a222b961834.png)

It was marked bad in a lot of trials, but not in all of them.

![figure_3](https://user-images.githubusercontent.com/428273/32266941-174d3bd4-bef2-11e7-8e8d-dc25d42683d1.png)

**Comment by wmvanvliet** [comment]
The data is pretty noisy overall, maybe that has something to do with it?

**Comment by dengemann** [comment]
Good question ...
You can of course introduce rules and just update this rejection matrix.

**Comment by jasmainak** [comment]
@dengemann "bayesian optimization" works better than "random search": that is for sure: and it is the default too as far as I remember. We had "random search" in one of the examples only because it was slightly faster.

@wmvanvliet if you share the data, I can take a look
